### PR TITLE
base for include-filter

### PR DESCRIPTION
**Pull request by KittenHero**
based on issue #8

### CODE REVIEW

**Comment by kakulukia** [comment]
you can make your life easier with

    flake8 --install-hook git

**Comment by kakulukia** [comment]
:)

**Comment by KittenHero** [comment]
thanks, will try

**Comment by kakulukia** [comment]
please include your markdown include as a test for the new code

**Comment by KittenHero** [comment]
_my_ markdown include?

I can't use a mark down filter without implementing a parser or importing it as a dependency

I can maybe manage a ROT13 filter

**Comment by kakulukia** [comment]
Well i meant to include the library in the Pipfile to have it available for testing. :)

**Comment by KittenHero** [comment]
@kakulukia I'm on a break with low internet connectivity at the moment an won't be able to work on it till March

**Comment by kakulukia** [comment]
okay, thx for the notice .. im not in a rush :) enjoy your distraction free time ! :)

**Comment by kakulukia** [comment]
status check?

**Comment by KittenHero** [comment]
I haven't been working on it, but I can try and get it done if anyone needs
the feature

**Comment by kakulukia** [comment]
Need would not be the word here. I just don’t want to have issues staying
open.

Take your pick! :)

> --

Mit besten Grüßen
Andy

**Pull request closed without merging**
