### PR TITLE
Fix relative includes in Jinja extension

### PR DESCRIPTION
**Pull request by Yoshi325**
Also fixes non-pug includes (they were being parsed as pug).

Issue #78

### CODE REVIEW

**Comment by kakulukia** [comment]
Hi @Yoshi325 ,

thanks for the PR! As i have nearly no time reviewing this, could you please also add a test case that can verify your changes?

Thanks already!

**Comment by Yoshi325** [comment]
I'll do my best!

**Comment by kakulukia** [comment]
Thanks!

**Comment by Yoshi325** [comment]
I am running into trouble following the README to run the testsuite. I poetry artifacts in the project, but the makefile uses pipenv. Which of those tools to should I be trying to make work for me?

**Comment by kakulukia** [comment]
i obviously have to update this!
Please use those commands:
```
poetry install
make test
```

I just did a fresh checkout and this worked: 273 passed, 1 warning in 0.98s

**Comment by kakulukia** [comment]
Hey @Yoshi325 ,

did you continue on this PR? Id like to either merge or close it now as a lot of time has passed.

**Pull request closed without merging**
