### PR TITLE
Fix recursive include (jinja + Django + html)

### PR DESCRIPTION
**Pull request by KittenHero**

### CODE REVIEW

**Comment by kakulukia** [comment]
Just to be sure, your changes add recursive includes rather than fixing a bug right?
Could you please also add a test case for that?

Im note sure if i ever used that feature .. what does a recursive include in a pug template look like?

**Comment by KittenHero** [comment]
Yea, It's a half fix, since you can already have recursive includes, but only the outer most include opens the file from the right directory

will write tests :+1:

**Comment by KittenHero** [comment]
I added the tests, but it broke Django and html because I didn't fix those :(

**Comment by KittenHero** [comment]
as of the last commit, html includes fail because of white space, I honestly have no idea what's wrong with django

**Comment by KittenHero** [comment]
Okay, fixed Django and html, but the code is a little bit ugly (sorry)

**Comment by kakulukia** [comment]
Will have a look at the „ugly“ code and thx for fixing the other two

**Comment by kakulukia** [comment]
Just by looking at your test case I still don’t get it. What’s the actual benefit of this way of including Mixins? Could you point that out in a few sentences for the readme? My goal for the next few days is to get rid of the general pug to html example and to show off the really cool parts like I started to right below.

**Comment by KittenHero** [comment]
I don't really have any good reason, I just create seperate pug files for each component and I didn't want to put too many components that are used together in the same file

**Pull request merged**
