### PR TITLE
Fixes #65: pypugjs.ext.html.Compiler did not escape interpolated strings

### LINKED ISSUE #65: `pypugjs.ext.html.Compiler` does not escape
* pypugjs version: 5.9.4

`pypugjs.ext.html.Compiler.interpolate` never uses the `escape` parameter, which is inconsistent with Pug templating.

Fix is easy -- change replacement to escape if escape is set.

### PR DESCRIPTION
**Pull request by wwoods**
See commit. If approved, please bump version and release, since this creates a vulnerability in some of my other code. Thanks!

### CODE REVIEW

**Comment by wwoods** [comment]
Looks like GitHub isn't linking correctly, so... this solves #65

**Comment by kakulukia** [comment]
Strange that the automatic tests are run but not shown in here .. its failing .. could you have a look and fix it .. you can have that new version instantly once the tests are green :)

**Comment by kakulukia** [comment]
https://travis-ci.org/github/kakulukia/pypugjs/jobs/734069241

**Comment by wwoods** [comment]
Hm, the test certainly passes locally. Even when run with `make coverage`, which I believe is what Travis CI does. I wonder if the CI suite is configured incorrectly? If it's using the old verison of the code for some reason?

**Comment by wwoods** [comment]
OH! Nevermind. The html compiler is fine. It looks like fixing this bug revealed bugs in the Django and Mako writers too.

**Comment by wwoods** [comment]
@kakulukia Ok, fixed. Mako was a similar fix to HTML, and Django needed a special case for strings (instead of variables) inside of an interpolation.

**Comment by kakulukia** [comment]
The new version is up.

**Comment by wwoods** [comment]
Thanks! Much appreciated.

**Pull request merged**
