### PR TITLE
WIP: Fix specifying attributes without commas.

### PR DESCRIPTION
**Pull request by vlad1777d**
I don't really quess what's going on and why state there should be == 2.

### CODE REVIEW

**Comment by kakulukia** [comment]
Me neither and since it aint braking the tests .. its better to simplify the code by removing all nonsens.

**Comment by vlad1777d** [comment]
@kakulukia , so can it be merged ?)

**Comment by kakulukia** [comment]
That small deletion removes the need for commas? I thought you were still in the process, because this seemed too weird. Consider it merged.

**Comment by vlad1777d** [comment]
Yeah, it's not very obvious parser, as for me.
So I don't use it as a plugin to Jinja right now.
I compile .pug to .jinja, after .jinja to .html. 
So I can more-lees see reasons of errors.

**Comment by vlad1777d** [comment]
Yes, it works, closing it.

**Pull request merged**
